apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: vote-app-result
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nodejs-010-centos7
    labels:
      build: vote-app-demo
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
  spec:
    tags:
      - name: latest
        annotations:
          openshift.io/imported-from: openshift/nodejs-010-centos7
        from:
          kind: DockerImage
          name: openshift/nodejs-010-centos7
        generation: 2
        importPolicy: {}
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: vote-app-result
    name: vote-app-result
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: vote-app-result:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: vote-app-result
    name: vote-app-result
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: vote-app-result:latest
    postCommit: {}
    resources:
      limits:
        cpu: 731m
        memory: 1Gi
      requests:
        cpu: 18m
        memory: 256Mi
    runPolicy: Serial
    source:
      contextDir: result-app
      git:
        uri: 'https://github.com/juniorjbn/demo-voting-ops.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-010-centos7:latest
      type: Source
    triggers:
    - github:
        secret: V2T0HmolZm1SzULGUNq6
      type: GitHub
    - generic:
        secret: 46QfQy0eN-XPFIAtPoBm
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: vote-app-result
    name: vote-app-result
  spec:
    replicas: 1
    selector:
      app: vote-app-result
      deploymentconfig: vote-app-result
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.vote-app-result.image.entrypoint: '["container-entrypoint","/bin/sh","-c","$STI_SCRIPTS_PATH/usage"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: vote-app-result
          deploymentconfig: vote-app-result
      spec:
        containers:
        - image: ""
          imagePullPolicy: Always
          name: vote-app-result
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "db"
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "db"
                  key: password
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vote-app-result
        from:
          kind: ImageStreamTag
          name: vote-app-result:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: vote-app-result
    name: vote-app-result
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 4000
    selector:
      app: vote-app-result
      deploymentconfig: vote-app-result
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: vote-app-result
    labels:
      app: vote-app-result
  spec:
    host: ''
    to:
      kind: Service
      name: vote-app-result
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
  status: {}